# -*- coding: utf-8 -*-
"""H12_An. arabiensis_Malawi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptLcgKwOYSWGm7SKZigya6lidCilVP5W
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q --no-warn-conflicts malariagen_data

import warnings
warnings.simplefilter(action='ignore', category=Warning)

import malariagen_data

try:
    from google.colab import drive
    drive.mount("drive")
except ImportError:
    pass

results_dir = "drive/MyDrive/malariagen_data_cache"

ag3 = malariagen_data.Ag3(results_cache=results_dir)
ag3

sample_sets=["AG1000G-MW"]

ag3.plot_h12_gwss(
    contig="2L",
    analysis="gamb_colu_arab",
    window_size=1500,
    sample_sets=sample_sets,
    sample_query="taxon =='arabiensis'",
)